export const searchIndex = [
  { label: 'AI & LLM Integration', path: '/services/ai-llm-integration', category: 'Services' },
  { label: 'Custom Software Development', path: '/services/custom-software-development', category: 'Services' },
  { label: 'Web & Mobile Development', path: '/services/web-mobile-development', category: 'Services' },
  { label: 'DevOps & Cloud', path: '/services/devops-cloud', category: 'Services' },
  { label: 'AI Automation', path: '/services/ai-automation', category: 'Services' },
  { label: 'SIEM', path: '/services/siem', category: 'Services' },
  { label: 'SOAR', path: '/services/soar', category: 'Services' },
  { label: 'SecOps', path: '/services/secops', category: 'Services' },
  { label: 'Performance Marketing', path: '/services/performance-marketing', category: 'Services' },
  { label: 'Technical SEO', path: '/services/technical-seo', category: 'Services' },
  { label: 'Growth SEO', path: '/services/growth-seo', category: 'Services' },
  { label: 'Paid Advertising', path: '/services/paid-advertising', category: 'Services' },
  { label: 'Social Media Marketing', path: '/services/social-media-marketing', category: 'Services' },
  { label: 'FinTech', path: '/solutions/fintech', category: 'Solutions' },
  { label: 'HealthTech', path: '/solutions/healthtech', category: 'Solutions' },
  { label: 'eCommerce', path: '/solutions/ecommerce', category: 'Solutions' },
  { label: 'Logistics', path: '/solutions/logistics', category: 'Solutions' },
  { label: 'EdTech', path: '/solutions/edtech', category: 'Solutions' },
  { label: 'LegalTech', path: '/solutions/legaltech', category: 'Solutions' },
  { label: 'PropTech', path: '/solutions/proptech', category: 'Solutions' },
  { label: 'HR Technology', path: '/solutions/hrtech', category: 'Solutions' },
  { label: 'GovTech', path: '/solutions/govtech', category: 'Solutions' },
  { label: 'SaaS', path: '/solutions/saas', category: 'Solutions' },
  { label: 'Media & Entertainment', path: '/solutions/media', category: 'Solutions' },
  { label: 'Manufacturing', path: '/solutions/manufacturing', category: 'Solutions' },
  { label: 'Services Overview', path: '/services', category: 'Pages' },
  { label: 'Solutions Overview', path: '/solutions', category: 'Pages' },
  { label: 'About Us', path: '/about', category: 'Pages' },
  { label: 'Contact', path: '/contact', category: 'Pages' },
  { label: 'Careers', path: '/careers', category: 'Pages' },
];
